name: 'newmethod'
on: [workflow_dispatch]

defaults:
  run:
    working-directory: ./

jobs:

  rerun_dev_deployment:
    name: 'newmethod'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: get-version-from-file
      id: set-version-number
      run: |
        TEXT=$(cat ./version.txt)
        echo "name=version::${TEXT//'%'/'%25'}" >> $GITHUB_OUTPUT

    - name: print-to-screen
      id: echo-version
      run: |
        echo ${{ steps.set-version-number.$GITHUB_OUTPUT }} 
    